apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tkn-pvc-cf-sample-app-nodejs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
